#!/usr/bin/env bash

####################################################################
####################################################################
# Autoload scripts (do not touch this section)
####################################################################

readonly DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
readonly DOKMAN_DIR="${DIR}/:dokmanDirName:"
source "${DOKMAN_DIR}/helpers/autoload.sh"

autoload "${DOKMAN_DIR}/helpers"

####################################################################
####################################################################
# Script setup part (modify it to fit you needs)
####################################################################

function usage
{
    write "Script for installing {site} docker setup"
    write ""
    write "   -h | --help      for this help message"
    write "   -v | --verbose   for more verbose output"
}

verbose=0
while [ "$1" != "" ]; do
    case $1 in
        -v | --verbose )        verbose=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        # add your own switches and logic
    esac
    shift
done

####################################################################
####################################################################
# Custom function (user defined)
####################################################################










####################################################################
####################################################################
# Installation part (user defined)
####################################################################









