#!/usr/bin/env bash

set -e

readonly SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
readonly DOKMAN_DIR="${SCRIPT_DIR}/:dokmanDirName:"
source "${DOKMAN_DIR}/autoload.sh"

if [ $# -eq 0 ]; then
    info "No arguments provided, printing out help"
    cat "${DOKMAN_DIR}/help/run"
    exit 0
fi

runDockerContainer ${SCRIPT_DIR} ${@}
